### ISSUE TITLE
🐛 [BUG] - shows transaction as successful but it wasn’t 

### ISSUE THREAD

**Issue by Periwinkleplur** [helius-labs/xray#182]
### Description

solscan link: https://solscan.io/tx/fAsutqP97uqtNJ21Pm3gVdGwqTXD1nBfHKAzQYy4D1ytGoeoywbitpqcuP2fS2kWSHNXyybDtLjGp9FrojD2B7X
xray link: https://xray.helius.xyz/tx/fAsutqP97uqtNJ21Pm3gVdGwqTXD1nBfHKAzQYy4D1ytGoeoywbitpqcuP2fS2kWSHNXyybDtLjGp9FrojD2B7X

this is an attempt to purchase an item on nightmarket listed on magic eden. transaction did not go through like solscan shows.

### Reproduction URL

what

### Reproduction steps

```bash
see description
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Safari

### OS

Mac

**Comment by ssamkkim** [comment]
Thanks for the report! Aware of this currently, Helius doesn't show failed transactions on their wallet transaction endpoint so I think that might be why it's the way it is currently but will find a way to change label depending on the tx.

**Comment by ssamkkim** [comment]
Sorry for the late response, this should be good now with this pr.
https://github.com/helius-labs/xray/pull/193

**Comment by Periwinkleplur** [comment]
damn right late response.
jk thank you.

**Comment by ssamkkim** [comment]
> LMAO yea my b...
