### ISSUE TITLE
🐛 [BUG] - make search button work

### ISSUE THREAD

**Issue by davidediak** [helius-labs/xray#254]
### Description

Currently, the "icon-button" is not working.

![image](https://github.com/helius-labs/xray/assets/27508143/87ef23f9-1e25-4cd2-941a-ad308ca8c7bb)

Since it's a button, I'd expect to have the search start when I click on it

### Reproduction URL

https://xray.helius.xyz/?network=mainnet

### Browsers

Chrome

### OS

Linux

**Comment by 0xIchigo** [comment]
Resolved with PR #255
